version: '3'
services:
  db:
    image: mdillon/postgis:9.6-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdjango_dev

  migrationdb:
    build: .
    image: migration_doc
    command: bash -c "sleep 10 && python manage.py migrate"
    volumes:
      - .:/test_django_doc
    environment:
      - DB_NAME=testdjango_dev
      - DB_HOST=db
      - DB_PORT=5432
      - DB_EXTERNAL=postgresql://postgres:postgres@db:5432/testdjango_dev
    depends_on:
      - db


  loaddata:
    build: .
    image: loaddata_doc
    command: bash -c "sleep 10 && python manage.py loaddata seeds/user.json"
    volumes:
      - .:/test_django_doc
    environment:
      - DB_NAME=testdjango_dev
      - DB_HOST=db
      - DB_PORT=5432
      - DB_EXTERNAL=postgresql://postgres:postgres@db:5432/testdjango_dev
    depends_on:
      - migrationdb

  web:
    build: .
    container_name: test_django_doc
    command: bash -c "sleep 10 && python manage.py runserver 0.0.0.0:5000"
    ports:
      - 5000:5000
    volumes:
      - .:/test_django_doc
    environment:
      - DB_NAME=testdjango_dev
      - DB_HOST=db
      - DB_PORT=5432
      - DB_EXTERNAL=postgresql://postgres:postgres@db:5432/testdjango_dev
    depends_on:
      - loaddata

