# Generated by Django 3.1.5 on 2021-01-24 23:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Point')),
                ('client_id', models.IntegerField(verbose_name='Client Id')),
                ('client_name', models.CharField(max_length=45, verbose_name='Client Name')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dataset')),
            ],
        ),
    ]
